# Use the official Golang image as a base image
FROM golang:1.20 AS builder

# Set the working directory
WORKDIR /app

# Copy the Go module files
COPY go.mod go.sum ./

# Download the dependencies
RUN go mod download

# Copy the source code and generated protobuf code
COPY paymentservice/ ./paymentservice/
COPY generated/ ./generated/
COPY etrace/ ./etrace/

# Build the binary
RUN CGO_ENABLED=0 GOOS=linux go build -o payment_service_server ./paymentservice/cmd/main.go

# Start a new stage from scratch
FROM alpine:latest

# Set the working directory
WORKDIR /root/

# Copy the binary from the previous stage
COPY --from=builder /app/payment_service_server .

# Expose the server port
EXPOSE 50052

# Run the binary
CMD ["./payment_service_server"]
